### ISSUE TITLE
Server stops working if the variable conditions include the variable name.

### ISSUE THREAD

**Issue by mmuller** [instedd/aida#126]
Engine version: 0.5.1

Error detail:
https://sentry.io/instedd/aida-staging/issues/470648826/

Screenshot:
![image](https://user-images.githubusercontent.com/518152/36558300-599dc7c4-17e9-11e8-9087-4bbe52ff6f2a.png)

**Comment by matiasgarciaisaia** [comment]
Has already been solved. The server is responding a 422 - unprocessable entity - code:

```
app_1    | [info] POST /api/bots
app_1    | [debug] Processing with AidaWeb.BotController.create/2
app_1    |   Parameters: %{"bot" => %{"manifest" => %{"channels" => [%{"access_token" => "[redacted]", "type" => "websocket"}], "front_desk" => %{"clarification" => %{"message" => %{"en" => "Is it more clear now?", "es" => "Is it more clear now?"}}, "greeting" => %{"message" => %{"en" => "Hi there!", "es" => "Hi there!"}}, "introduction" => %{"message" => %{"en" => "I can do stuff", "es" => "I can do stuff"}}, "not_understood" => %{"message" => %{"en" => "Didn't get you :/", "es" => "Didn't get you :/"}}, "threshold" => 0.5}, "languages" => ["en", "es"], "public_keys" => ["[redacted]"], "skills" => [%{"explanation" => "To chat in english, say 'english'", "languages" => %{"en" => ["english", "en"], "es" => ["español", "castellano"]}, "reply_to_unsupported_language" => false, "type" => "language_detector"}], "variables" => [%{"name" => "age", "overrides" => [%{"relevant" => "$(age)<18", "values" => %{"en" => "", "es" => ""}}, %{"relevant" => "$(age)>=18", "values" => %{"en" => "", "es" => ""}}], "values" => %{"en" => "", "es" => ""}}], "version" => "1"}, "temp" => true}}
app_1    |   Pipelines: [:api]
app_1    | [warn] Error while parsing manifest: Invalid expression: '$(age)<18' []
app_1    | [info] Sent 422 in 46ms
app_1    | [debug] AidaWeb.BotController halted in :validate_params/2
ui_1     | Failed to preview bot: Unprocessable Entity (422)
ui_1     | F, [2018-06-07T15:28:43.559609 #6] FATAL -- : [ce0500ac-edd1-45df-83d0-a227adecaf57]
ui_1     | F, [2018-06-07T15:28:43.559708 #6] FATAL -- : [ce0500ac-edd1-45df-83d0-a227adecaf57] NoMethodError (undefined method `each' for nil:NilClass):
ui_1     | F, [2018-06-07T15:28:43.559738 #6] FATAL -- : [ce0500ac-edd1-45df-83d0-a227adecaf57]
ui_1     | F, [2018-06-07T15:28:43.559821 #6] FATAL -- : [ce0500ac-edd1-45df-83d0-a227adecaf57] app/services/publish_bot.rb:30:in `rescue in preview'
ui_1     | [ce0500ac-edd1-45df-83d0-a227adecaf57] app/services/publish_bot.rb:21:in `preview'
ui_1     | [ce0500ac-edd1-45df-83d0-a227adecaf57] app/controllers/api/bots_controller.rb:55:in `preview'
```

**Comment by nekron** [comment]
The interpolation in expressions  should be done with curly brackets instead of parenthesis, as in the original screenshot.

**Comment by mmuller** [comment]
Working properly in version d04523a
